### PR TITLE
Split Channel FSM into multiple files

### PR DESCRIPTION
**Pull request by sstone**
We use a language feature introduced with Kotlin 1.5 to split the channel state machine into multiple files (one per state) which makes it imho much easier to work with.
There are no functional changes.

### CODE REVIEW

**Comment by sstone** [comment]
I was trying to split Channel.kt into multiple files while preserving git history for each new file, it does not seem to have worked I'll try again (but the end result should be the same).

**Review by dpad85 — APPROVED** [review]

**Review by t-bast — DISMISSED** [review]
:+1:

**Comment by sstone** [comment]
I've redone the splitting/cleaning of Channel.kt to preserve git history/blame info in the new channel states.

**Review by t-bast — APPROVED** [review]
Interesting approach, I didn't know that trick!

**Review by dpad85 — APPROVED** [review]

**Pull request merged**
